
HISTFILE=$HOME/.zsh_history
HISTSIZE=100000
SAVEHIST=$HISTSIZE

alias vim=nvim
alias d="kitty +kitten diff"
alias ls='ls --color=tty'
alias grep='rg'

bindkey "\e[3~" delete-char 
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
bindkey -e

# Remove older duplicate entries from history.
setopt hist_ignore_all_dups
# Remove superfluous blanks from history items.
setopt hist_reduce_blanks
# Save history entries as soon as they are entered.
setopt inc_append_history
# Share history between different instances of the shell.
setopt share_history

setopt auto_cd
#setopt correct_all

# Automatically list choices on ambiguous completion.
setopt auto_list 
# Automatically use menu completion.
setopt auto_menu
# Move cursor to end if word had one match.
setopt always_to_end

zstyle ':completion:*' menu select # select completions with arrow keys
zstyle ':completion:*' group-name '' # group results by category
zstyle ':completion:::::' completer _expand _complete _ignored _approximate # enable approximate matches for completion

# Exports
source ~/.exports

# Call neofetch
#neofetch

fpath=(~/.zsh/completions $fpath)

fpath+=~/.zfunc

autoload -Uz compinit

typeset -i updated_at=$(date +'%j' -r ~/.zcompdump 2>/dev/null || stat -f '%Sm' -t '%j' ~/.zcompdump 2>/dev/null)
if [ $(date +'%j') != $updated_at ]; then
	compinit -i
else
	compinit -C -i
fi

zmodload -i zsh/complist

# Load antibody plugins.
source ~/.zsh_plugins.sh

[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

eval "$(direnv hook zsh)"
#eval `keychain --eval --agents ssh id_rsa`

eval "$(rbenv init -)"

