config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_by_default: false
  longkey: false
dotfiles:
  f_exports:
    dst: ~/.exports
    src: exports
  f_init.vim:
    dst: ~/.config/nvim/init.vim
    src: config/nvim/init.vim
  f_keybindings.json:
    dst: ~/.config/Code/User/keybindings.json
    src: config/Code/User/keybindings.json
  f_settings.json:
    dst: ~/.config/Code/User/settings.json
    src: config/Code/User/settings.json
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
profiles:
  daedalus:
    dotfiles:
    - f_zshrc
    - f_exports
    - f_keybindings.json
    - f_settings.json
    - f_init.vim
