config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_by_default: false
  longkey: false
  workdir: ~/.config/dotdrop
dotfiles:
  d_geometry-plugins:
    dst: ~/geometry-plugins
    src: geometry-plugins
  f_config:
    dst: ~/.config/termite/config
    src: config/termite/config
  f_config.yml:
    dst: ~/.config/wtf/config.yml
    src: config/wtf/config.yml
  f_exports:
    dst: ~/.exports
    src: exports
  f_gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
  f_init.vim:
    dst: ~/.config/nvim/init.vim
    src: config/nvim/init.vim
  f_init_scrollback_pager.vim:
    dst: ~/.config/nvim/init_scrollback_pager.vim
    src: config/nvim/init_scrollback_pager.vim
  f_keybindings.json:
    dst: ~/.config/Code/User/keybindings.json
    src: config/Code/User/keybindings.json
  f_kitty.conf:
    dst: ~/.config/kitty/kitty.conf
    src: config/kitty/kitty.conf
  f_settings.json:
    dst: ~/.config/Code/User/settings.json
    src: config/Code/User/settings.json
  f_tags.patch:
    dst: ~/aur/packages/dwm/src/tags.patch
    src: aur/packages/dwm/src/tags.patch
  f_terminal.patch:
    dst: ~/aur/packages/dwm/src/terminal.patch
    src: aur/packages/dwm/src/terminal.patch
  f_theme.patch:
    dst: ~/aur/packages/dwm/src/theme.patch
    src: aur/packages/dwm/src/theme.patch
  f_volume.patch:
    dst: ~/aur/packages/dwm/src/volume.patch
    src: aur/packages/dwm/src/volume.patch
  f_zsh_plugins.txt:
    dst: ~/.zsh_plugins.txt
    src: zsh_plugins.txt
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
profiles:
  Icarus:
    dotfiles:
    - f_kitty.conf
    - f_init_scrollback_pager.vim
    - f_init.vim
    - f_exports
    - f_zsh_plugins.txt
    - f_zshrc
    - f_keybindings.json
    - f_settings.json
    - f_gitconfig
    - d_geometry-plugins
    - f_config.yml
  daedalus:
    dotfiles:
    - f_zshrc
    - f_exports
    - f_keybindings.json
    - f_settings.json
    - f_init.vim
    - f_zsh_plugins.txt
    - f_config
    - f_kitty.conf
    - f_tags.patch
    - f_terminal.patch
    - f_theme.patch
    - f_volume.patch
