config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_by_default: false
  longkey: false
dotfiles:
  f_config:
    dst: ~/.config/termite/config
    src: config/termite/config
  f_exports:
    dst: ~/.exports
    src: exports
  f_init.vim:
    dst: ~/.config/nvim/init.vim
    src: config/nvim/init.vim
  f_keybindings.json:
    dst: ~/.config/Code/User/keybindings.json
    src: config/Code/User/keybindings.json
  f_kitty.conf:
    dst: ~/.config/kitty/kitty.conf
    src: config/kitty/kitty.conf
  f_settings.json:
    dst: ~/.config/Code/User/settings.json
    src: config/Code/User/settings.json
  f_zsh_plugins.txt:
    dst: ~/.zsh_plugins.txt
    src: zsh_plugins.txt
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
profiles:
  daedalus:
    dotfiles:
    - f_zshrc
    - f_exports
    - f_keybindings.json
    - f_settings.json
    - f_init.vim
    - f_zsh_plugins.txt
    - f_config
    - f_kitty.conf
