#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

export POLYBAR_PATH="$HOME/.config/polybar"

echo $SCRIPTPATH
echo $POLYBAR_PATH

#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down


#boot compton or picom if it exists
if [ -x "$(command -v compton)" ]; then
  compton &> /dev/null & 
elif [ -x "$(command -v picom)" ]; then
  picom &> /dev/null & 
fi

#set the theme.toml config
echo "LoadTheme $SCRIPTPATH/theme.toml" > $XDG_RUNTIME_DIR/leftwm/commands.pipe


#set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale $SCRIPTPATH/wall.png
fi


index=0
#monitor="$(polybar -m | grep +0+0 | sed s/:.*// | tac)"
monitor="$(polybar -m | grep primary | sed s/:.*// | tac)"

leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do 
  barname="mainbar$index"
  echo $barname
  #monitor=$monitor offsetx=$x width=$width polybar top -c $POLYBAR_PATH/config.ini &> /dev/null &
  monitor=$monitor offsetx=$x width=$width polybar -c $SCRIPTPATH/polybar.config $barname 2>&1 | tee -a /tmp/polybar_leftwm.log & disown
  echo $monitor
  let index=index+1
done

